import React, { useState, useRef, useEffect, useCallback } from 'react';
import { aiChatStream, ChatMessage } from './utils/api';
import './ChatPanel.css';

interface ChatPanelProps {
  briefContext: string | null;
  isOpen: boolean;
  onClose: () => void;
}

// ── Chat Export Helpers ───────────────────────────────────────────

/** Convert a single message to plain-text with light markdown */
function messageToText(msg: ChatMessage): string {
  const label = msg.role === 'user' ? '🗣️ YOU' : '⚖️ LEXASSIST AI';
  return `${label}\n${'─'.repeat(40)}\n${msg.content}\n`;
}

/** Copy full conversation to clipboard as formatted text */
async function copyConversation(messages: ChatMessage[]): Promise<boolean> {
  const header = `LEXASSIST AI — LEGAL CONSULTATION\nDate: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}\n${'═'.repeat(50)}\n\n`;
  const body = messages.map(messageToText).join('\n');
  const footer = `\n${'═'.repeat(50)}\nGenerated by LexAssist AI • Indian Law Specialist\nhttps://lex-assist.vercel.app\n`;
  try {
    await navigator.clipboard.writeText(header + body + footer);
    return true;
  } catch {
    return false;
  }
}

/** Build a self-contained HTML document and open it for print / save-as-PDF */
function exportAsDocument(messages: ChatMessage[], briefContext: string | null) {
  const dateStr = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
  const timeStr = new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });

  // Convert markdown-like chat content → HTML
  const toHtml = (text: string) => {
    return text
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/`(.+?)`/g, '<code>$1</code>')
      .replace(/^### (.+)$/gm, '<h4>$1</h4>')
      .replace(/^## (.+)$/gm, '<h3>$1</h3>')
      .replace(/^[-*] (.+)$/gm, '<li>$1</li>')
      .replace(/^(\d+)\. (.+)$/gm, '<li>$2</li>')
      .replace(/\n/g, '<br/>');
  };

  const messagesHtml = messages.map(msg => {
    const isUser = msg.role === 'user';
    return `
      <div class="msg ${isUser ? 'user' : 'ai'}">
        <div class="msg-label">${isUser ? '🗣️ Client Query' : '⚖️ LexAssist AI Response'}</div>
        <div class="msg-body">${toHtml(msg.content)}</div>
      </div>`;
  }).join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>LexAssist AI — Legal Consultation (${dateStr})</title>
<style>
  @page { margin: 20mm 18mm; size: A4; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Georgia', 'Times New Roman', serif; color: #1a1a1a; line-height: 1.65; background: #fff; }
  .doc { max-width: 800px; margin: 0 auto; padding: 32px 24px; }

  /* Letterhead */
  .header { text-align: center; border-bottom: 3px double #0a2e5c; padding-bottom: 18px; margin-bottom: 24px; }
  .header h1 { font-size: 1.6rem; color: #0a2e5c; letter-spacing: 1px; margin-bottom: 4px; }
  .header .subtitle { font-size: 0.85rem; color: #6b7280; font-style: italic; }
  .header .meta { font-size: 0.78rem; color: #9ca3af; margin-top: 8px; }

  /* Context badge */
  .context-note { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 8px 14px; font-size: 0.82rem; color: #166534; margin-bottom: 20px; }

  /* Messages */
  .msg { margin-bottom: 20px; page-break-inside: avoid; }
  .msg-label { font-weight: 700; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 6px; }
  .msg.user .msg-label { color: #0a2e5c; }
  .msg.ai .msg-label { color: #7c3aed; }
  .msg-body { padding: 14px 18px; border-radius: 8px; font-size: 0.92rem; }
  .msg.user .msg-body { background: #f8fafc; border-left: 4px solid #0a2e5c; }
  .msg.ai .msg-body { background: #faf5ff; border-left: 4px solid #7c3aed; }
  .msg-body h3 { font-size: 1.05rem; color: #0a2e5c; margin: 12px 0 6px; }
  .msg-body h4 { font-size: 0.95rem; color: #1e40af; margin: 10px 0 4px; }
  .msg-body li { margin-left: 24px; margin-bottom: 3px; }
  .msg-body strong { color: #0a2e5c; }
  .msg-body code { background: #f1f5f9; padding: 1px 5px; border-radius: 3px; font-size: 0.85em; color: #7c3aed; font-family: 'Courier New', monospace; }

  /* Footer */
  .footer { border-top: 2px solid #e5e7eb; margin-top: 32px; padding-top: 14px; text-align: center; font-size: 0.72rem; color: #9ca3af; }
  .footer .brand { font-weight: 700; color: #0a2e5c; }

  /* Print adjustments */
  @media print {
    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .doc { padding: 0; }
    .no-print { display: none !important; }
  }

  /* Action bar (hidden on print) */
  .actions { display: flex; gap: 10px; justify-content: center; margin-bottom: 24px; }
  .actions button { padding: 10px 22px; border: none; border-radius: 8px; font-size: 0.88rem; font-weight: 600; cursor: pointer; transition: all 0.2s; }
  .btn-print { background: #0a2e5c; color: #fff; }
  .btn-print:hover { background: #143d7a; }
  .btn-copy { background: #f3f4f6; color: #374151; border: 1px solid #d1d5db; }
  .btn-copy:hover { background: #e5e7eb; }
</style>
</head>
<body>
<div class="doc">
  <div class="actions no-print">
    <button class="btn-print" onclick="window.print()">🖨️ Print / Save as PDF</button>
    <button class="btn-copy" onclick="copyAll()">📋 Copy Text</button>
  </div>

  <div class="header">
    <h1>⚖️ LexAssist AI</h1>
    <div class="subtitle">AI-Powered Legal Consultation — Indian Law Specialist</div>
    <div class="meta">${dateStr} at ${timeStr} • ${messages.length} message${messages.length !== 1 ? 's' : ''}</div>
  </div>

  ${briefContext ? '<div class="context-note">📋 <strong>Case context was loaded</strong> — AI responses are informed by the submitted case brief.</div>' : ''}

  ${messagesHtml}

  <div class="footer">
    <p><span class="brand">LexAssist AI</span> — Intelligent Legal Research & Strategy Platform</p>
    <p>This document was auto-generated from an AI consultation session. AI outputs are advisory only and do not constitute legal advice.</p>
    <p>© ${new Date().getFullYear()} LexAssist • <a href="https://lex-assist.vercel.app">lex-assist.vercel.app</a></p>
  </div>
</div>
<script>
function copyAll(){
  const msgs = document.querySelectorAll('.msg');
  let text = 'LEXASSIST AI — LEGAL CONSULTATION\\nDate: ${dateStr}\\n${'═'.repeat(50)}\\n\\n';
  msgs.forEach(m => {
    const label = m.querySelector('.msg-label')?.textContent || '';
    const body = m.querySelector('.msg-body')?.textContent || '';
    text += label + '\\n' + '─'.repeat(40) + '\\n' + body.trim() + '\\n\\n';
  });
  text += '${'═'.repeat(50)}\\nGenerated by LexAssist AI\\n';
  navigator.clipboard.writeText(text).then(() => {
    const btn = document.querySelector('.btn-copy');
    if(btn){ btn.textContent='✅ Copied!'; setTimeout(()=>{ btn.textContent='📋 Copy Text'; },2000); }
  });
}
</script>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  window.open(url, '_blank');
  // Revoke after a delay so the tab can load
  setTimeout(() => URL.revokeObjectURL(url), 60000);
}

const SUGGESTED_QUESTIONS = [
  "What are the strongest arguments for the petitioner?",
  "List all applicable sections and their provisions",
  "What precedents should I cite in court?",
  "What are the potential weaknesses in this case?",
  "Draft a summary of arguments for filing",
  "What evidence do I need to collect?",
  "Explain the limitation period for this case",
  "What interim reliefs can I seek?",
];

const ChatPanel: React.FC<ChatPanelProps> = ({ briefContext, isOpen, onClose }) => {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [isStreaming, setIsStreaming] = useState(false);
  const [streamingText, setStreamingText] = useState('');
  const [showShareMenu, setShowShareMenu] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);
  const cancelRef = useRef<(() => void) | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const shareMenuRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, streamingText]);

  // Focus input when opened
  useEffect(() => {
    if (isOpen && inputRef.current) {
      setTimeout(() => inputRef.current?.focus(), 300);
    }
  }, [isOpen]);

  // Close share menu on outside click
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (shareMenuRef.current && !shareMenuRef.current.contains(e.target as Node)) {
        setShowShareMenu(false);
      }
    };
    if (showShareMenu) document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [showShareMenu]);

  const handleExportDoc = () => {
    setShowShareMenu(false);
    exportAsDocument(messages, briefContext);
  };

  const handleCopyChat = async () => {
    const ok = await copyConversation(messages);
    if (ok) {
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    }
    setShowShareMenu(false);
  };

  const sendMessage = useCallback(async (text: string) => {
    if (!text.trim() || isStreaming) return;

    const userMsg: ChatMessage = { role: 'user', content: text.trim() };
    const newMessages = [...messages, userMsg];
    setMessages(newMessages);
    setInput('');
    setIsStreaming(true);
    setStreamingText('');

    let accumulated = '';

    const cancel = await aiChatStream(
      newMessages,
      briefContext,
      (chunk) => {
        accumulated += chunk;
        setStreamingText(accumulated);
      },
      () => {
        setMessages(prev => [...prev, { role: 'assistant', content: accumulated }]);
        setStreamingText('');
        setIsStreaming(false);
      },
      (error) => {
        setMessages(prev => [...prev, { role: 'assistant', content: `⚠️ Error: ${error}` }]);
        setStreamingText('');
        setIsStreaming(false);
      }
    );

    cancelRef.current = cancel;
  }, [messages, briefContext, isStreaming]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    sendMessage(input);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage(input);
    }
  };

  const handleStop = () => {
    if (cancelRef.current) {
      cancelRef.current();
      cancelRef.current = null;
    }
    if (streamingText) {
      setMessages(prev => [...prev, { role: 'assistant', content: streamingText + '\n\n[Stopped]' }]);
    }
    setStreamingText('');
    setIsStreaming(false);
  };

  const handleClear = () => {
    setMessages([]);
    setStreamingText('');
    setIsStreaming(false);
  };

  // Simple markdown-like rendering
  const renderContent = (text: string) => {
    // Convert markdown-style formatting
    const lines = text.split('\n');
    return lines.map((line, i) => {
      // Headers
      if (line.startsWith('### ')) {
        return <h4 key={i} className="chat-h4">{line.slice(4)}</h4>;
      }
      if (line.startsWith('## ')) {
        return <h3 key={i} className="chat-h3">{line.slice(3)}</h3>;
      }
      // Bold
      let processed = line.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
      // Inline code
      processed = processed.replace(/`(.+?)`/g, '<code>$1</code>');
      // Bullet points
      if (processed.startsWith('- ') || processed.startsWith('* ')) {
        return <li key={i} className="chat-li" dangerouslySetInnerHTML={{ __html: processed.slice(2) }} />;
      }
      // Numbered items
      const numMatch = processed.match(/^(\d+)\.\s/);
      if (numMatch) {
        return <li key={i} className="chat-li-num" dangerouslySetInnerHTML={{ __html: processed.slice(numMatch[0].length) }} />;
      }
      // Empty lines
      if (!processed.trim()) return <br key={i} />;
      // Normal paragraph
      return <p key={i} className="chat-p" dangerouslySetInnerHTML={{ __html: processed }} />;
    });
  };

  if (!isOpen) return null;

  return (
    <div className="chat-panel-overlay">
      <div className="chat-panel">
        {/* Header */}
        <div className="chat-header">
          <div className="chat-header-left">
            <div className="chat-ai-indicator">
              <span className="chat-ai-dot"></span>
              <span>LexAssist AI</span>
            </div>
            {briefContext && (
              <span className="chat-context-badge">Case context loaded</span>
            )}
          </div>
          <div className="chat-header-actions">
            {/* Share / Export */}
            <div className="chat-share-wrapper" ref={shareMenuRef}>
              <button
                onClick={() => setShowShareMenu(!showShareMenu)}
                className="chat-btn-ghost"
                title="Share conversation"
                disabled={messages.length === 0}
              >
                {copySuccess ? (
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#22c55e" strokeWidth="2.5"><path d="M20 6L9 17l-5-5"/></svg>
                ) : (
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M4 12v8a2 2 0 002 2h12a2 2 0 002-2v-8"/>
                    <polyline points="16 6 12 2 8 6"/>
                    <line x1="12" y1="2" x2="12" y2="15"/>
                  </svg>
                )}
              </button>
              {showShareMenu && messages.length > 0 && (
                <div className="chat-share-menu">
                  <button onClick={handleExportDoc} className="chat-share-option">
                    <span className="chat-share-icon">📄</span>
                    <div>
                      <div className="chat-share-title">Export as Document</div>
                      <div className="chat-share-desc">Formatted document • Print / Save as PDF</div>
                    </div>
                  </button>
                  <button onClick={handleCopyChat} className="chat-share-option">
                    <span className="chat-share-icon">📋</span>
                    <div>
                      <div className="chat-share-title">Copy to Clipboard</div>
                      <div className="chat-share-desc">Plain text • Paste anywhere</div>
                    </div>
                  </button>
                </div>
              )}
            </div>
            <button onClick={handleClear} className="chat-btn-ghost" title="Clear chat">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M3 6h18M8 6V4a2 2 0 012-2h4a2 2 0 012 2v2m3 0v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6h14"/>
              </svg>
            </button>
            <button onClick={onClose} className="chat-btn-ghost" title="Close">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M18 6L6 18M6 6l12 12"/>
              </svg>
            </button>
          </div>
        </div>

        {/* Messages */}
        <div className="chat-messages">
          {messages.length === 0 && !streamingText && (
            <div className="chat-welcome">
              <div className="chat-welcome-icon">⚖️</div>
              <h3>LexAssist AI Legal Assistant</h3>
              <p>Ask me anything about Indian law, your case strategy, applicable sections, or relevant precedents.</p>
              {briefContext && (
                <p className="chat-welcome-context">
                  I have your case brief loaded. Ask me questions about it!
                </p>
              )}
              <div className="chat-suggestions">
                {SUGGESTED_QUESTIONS.slice(0, briefContext ? 6 : 4).map((q, i) => (
                  <button
                    key={i}
                    className="chat-suggestion-chip"
                    onClick={() => sendMessage(q)}
                  >
                    {q}
                  </button>
                ))}
              </div>
            </div>
          )}

          {messages.map((msg, i) => (
            <div key={i} className={`chat-message chat-message-${msg.role}`}>
              <div className="chat-message-avatar">
                {msg.role === 'user' ? '👤' : '⚖️'}
              </div>
              <div className="chat-message-content">
                {msg.role === 'assistant' ? (
                  <div className="chat-markdown">{renderContent(msg.content)}</div>
                ) : (
                  <p>{msg.content}</p>
                )}
              </div>
            </div>
          ))}

          {/* Streaming response */}
          {isStreaming && streamingText && (
            <div className="chat-message chat-message-assistant">
              <div className="chat-message-avatar">⚖️</div>
              <div className="chat-message-content">
                <div className="chat-markdown">{renderContent(streamingText)}</div>
                <span className="chat-cursor">▌</span>
              </div>
            </div>
          )}

          {/* Loading indicator */}
          {isStreaming && !streamingText && (
            <div className="chat-message chat-message-assistant">
              <div className="chat-message-avatar">⚖️</div>
              <div className="chat-message-content">
                <div className="chat-thinking">
                  <span></span><span></span><span></span>
                </div>
              </div>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Input */}
        <form onSubmit={handleSubmit} className="chat-input-area">
          <div className="chat-input-wrapper">
            <textarea
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Ask about your case, legal provisions, precedents..."
              rows={1}
              disabled={isStreaming}
              className="chat-textarea"
            />
            {isStreaming ? (
              <button type="button" onClick={handleStop} className="chat-btn-stop" title="Stop generating">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                  <rect x="6" y="6" width="12" height="12" rx="2"/>
                </svg>
              </button>
            ) : (
              <button
                type="submit"
                disabled={!input.trim()}
                className="chat-btn-send"
                title="Send message"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M22 2L11 13M22 2l-7 20-4-9-9-4 20-7z"/>
                </svg>
              </button>
            )}
          </div>
          <div className="chat-input-footer">
            <span>Powered by LexAssist AI • Indian Law Specialist</span>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ChatPanel;
