services:
  - type: web
    name: lexassist-backend
    runtime: python
    buildCommand: cd legal_app/backend && pip install -r requirements.txt
    startCommand: cd legal_app/backend && gunicorn app:app
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: ASSEMBLY_AI_API_KEY
        sync: false
      - key: NEO4J_USERNAME
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_PUBLIC_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_API_ACCOUNT_KEY
        sync: false
      - key: REDIS_API_USER_KEY
        sync: false
      - key: INLEGALBERT_MODEL_PATH
        value: law-ai/InLegalBERT
      - key: HUGGINGFACE_TOKEN
        sync: false
    disk:
      name: huggingface-cache
      mountPath: /app/huggingface
      sizeGB: 2