steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'lexassist'
  - '--image=gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA'
  - '--region=europe-west1'
  - '--port=8000'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--memory=2Gi'
  - '--timeout=900s'
  - '--cpu=2'
  - '--min-instances=0'
  - '--max-instances=5'
  # Set each environment variable separately for cleaner configuration
  - '--set-env-vars=CLOUD_RUN=true'
  - '--set-env-vars=CORS_ALLOWED_ORIGINS=https://lex-assist.vercel.app,http://localhost:3000,http://localhost:3001,http://localhost:5173'
  - '--set-env-vars=CORS_ALLOW_CREDENTIALS=true'
  - '--set-env-vars=CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS,PATCH'
  - '--set-env-vars=CORS_ALLOW_HEADERS=Content-Type,Authorization,X-Requested-With,Accept,Origin'
  - '--set-env-vars=CORS_MAX_AGE=600'
  - '--set-env-vars=PORT=8000'

# Store images
images:
- 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA'

options:
  # Set the machine type to use for the build
  machineType: 'E2_HIGHCPU_8'
  # Specify logging mode to fix service account requirement
  logging: CLOUD_LOGGING_ONLY

# Increased timeout for ML model downloads (30 minutes)
timeout: '1800s'