steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'lexassist'
  - '--image=gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA'
  - '--region=europe-west1'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--memory=2Gi'
  - '--timeout=300s'
  - '--cpu=1'
  - '--min-instances=0'
  - '--max-instances=5'
  # Set environment variables as needed
  - '--set-env-vars=CLOUD_RUN=true,CORS_ALLOWED_ORIGINS=https://lex-assist.vercel.app,CORS_ALLOW_CREDENTIALS=true,CORS_ALLOW_METHODS=GET\,POST\,PUT\,DELETE\,OPTIONS\,PATCH,CORS_ALLOW_HEADERS=Content-Type\,Authorization\,X-Requested-With\,Accept\,Origin,CORS_MAX_AGE=600'

# Store images
images:
- 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA'

options:
  # Set the machine type to use for the build
  machineType: 'E2_HIGHCPU_8'
  # Increased timeout for ML model downloads (30 minutes)
  timeout: '1800s'
