# legal_app/backend/cloudbuild.yaml
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'legal_app/backend'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  dir: 'legal_app/backend'
  args: ['push', 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA']

# Deploy container image to Cloud Run with Secret Manager
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  dir: 'legal_app/backend'
  args:
  - 'run'
  - 'deploy'
  - 'lexassist'
  - '--image=gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA'
  - '--region=europe-west1'
  - '--port=8000'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--memory=2Gi'
  - '--timeout=900s'
  - '--cpu=2'
  - '--min-instances=0'
  - '--max-instances=5'
  - '--set-env-vars=CLOUD_RUN=true'
  - '--set-env-vars=USE_HF_INFERENCE_API=true'
  - '--set-env-vars=CORS_ALLOWED_ORIGINS=https://lex-assist.vercel.app,http://localhost:3000,http://localhost:3001,http://localhost:5173'
  - '--set-env-vars=CORS_ALLOW_CREDENTIALS=true'
  - '--set-env-vars=CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS,PATCH'
  - '--set-env-vars=CORS_ALLOW_HEADERS=Content-Type,Authorization,X-Requested-With,Accept,Origin'
  - '--set-env-vars=CORS_MAX_AGE=600'
  - '--set-secrets=SUPABASE_URL=supabase-url:latest'
  - '--set-secrets=SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key:latest'
  - '--set-secrets=HF_TOKEN=huggingface-token:latest'

images:
- 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'