# legal_app/backend/cloudbuild.yaml
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'legal_app/backend'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  dir: 'legal_app/backend'
  args: ['push', 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA']

# Deploy using environment variables file (more reliable approach)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  dir: 'legal_app/backend'
  args:
  - 'run'
  - 'deploy'
  - 'lexassist'
  - '--image=gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA'
  - '--region=europe-west1'
  - '--port=8000'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--memory=2Gi'
  - '--timeout=900s'
  - '--cpu=2'
  - '--min-instances=0'
  - '--max-instances=5'
  - '--env-vars-file=env-vars.yaml'
  - '--set-secrets=SUPABASE_URL=supabase-url:latest'
  - '--set-secrets=SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key:latest'
  - '--set-secrets=HF_TOKEN=huggingface-token:latest'
  
  # Log success message
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'echo'
  args:
  - 'Deployment completed successfully!'

images:
- 'gcr.io/$PROJECT_ID/lexassist:$COMMIT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'