# configs/deployment/render.yaml
services:
  # MCP Server API
  - type: web
    name: lexassist-mcp-server
    runtime: node  # Changed from "nodejs" to "node" (valid value)
    plan: starter
    buildCommand: cd mcp_server && npm install && npm run build
    startCommand: cd mcp_server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: gcp-starter
      - key: PINECONE_INDEX_NAME
        value: lexassist-legal-docs
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USERNAME
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: API_SETU_KEY
        sync: false
      - key: INDIAN_KANOON_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRY
        value: 24h
      - key: REDIS_URL
        sync: false

  # Legacy Backend API 
  - type: web
    name: lexassist-legal-app
    runtime: node  # Changed from "nodejs" to "node" (valid value)
    plan: starter
    buildCommand: cd legal_app && npm install && npm run build
    startCommand: cd legal_app && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      # Add necessary environment variables for the legacy app

  # Python Backend API with InLegalBERT
  - type: web
    name: lexassist-backend
    runtime: python  # Added required "runtime" property, removed invalid "env" property
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PINECONE_API_KEY
        value: pcsk_76Pk4Y_ABp8Yw7eMT2F9sjBAr5LwBMaqawpJZn5WdZ4DG2ozhJtkz2GvAniuK3YDudMAKb
      - key: ASSEMBLY_AI_API_KEY
        value: acd3d7ddea50411d85feba6dee6b179c
      - key: NEO4J_USERNAME
        value: neo4j
      - key: NEO4J_PASSWORD
        value: SvUkTb8OutU4Z-yS0L5o65z8TrJo9JTFRMk0aG8Q0Gw
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        value: https://meuyiktpkeomskqornnu.supabase.co
      - key: SUPABASE_ANON_PUBLIC_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ldXlpa3Rwa2VvbXNrcW9ybm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNDM0NDQsImV4cCI6MjA2MzYxOTQ0NH0.ADWjENLW1GdjdQjrrqjG8KtXndRoTxXy8zBffm4mweU
      - key: SUPABASE_JWT_SECRET
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ldXlpa3Rwa2VvbXNrcW9ybm51Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODA0MzQ0NCwiZXhwIjoyMDYzNjE5NDQ0fQ.YiAquC2_nY1Kid3EqDvnpqxpG_8mOgRP7wwjDhWQUyo
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: REDIS_API_ACCOUNT_KEY
        value: A5vw32vg4u6btip1t4dfa7j0mab54fsnw9jnyO2swoja85wp1
      - key: REDIS_API_USER_KEY
        value: A5vw32vg4u6btip1t4dfa7j0mab54fsnw9jnyO2swoja85wp1
      - key: INLEGALBERT_MODEL_PATH
        value: law-ai/InLegalBERT
      - key: HUGGINGFACE_TOKEN
        value: hf_zSAcaCWTaaJBHwImVPUChBsIFlaXgQFwG
    disk:
      name: huggingface-cache
      mountPath: /app/huggingface
      sizeGB: 2